stages:
  - test

integration_test:
  stage: test
  script:
    - echo "Running integration tests..."
    - # Add command to run your integration tests here (e.g., pytest, npm test, etc.)
  tags:
    - docker # Optional: Specify a runner tag if using a specific runner
